//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QQ2013.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QQ2013.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1_100 {
            get {
                object obj = ResourceManager.GetObject("_1_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap afternoon {
            get {
                object obj = ResourceManager.GetObject("afternoon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aio_head_normal {
            get {
                object obj = ResourceManager.GetObject("aio_head_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aio_quickbar_cut {
            get {
                object obj = ResourceManager.GetObject("aio_quickbar_cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aio_quickbar_face {
            get {
                object obj = ResourceManager.GetObject("aio_quickbar_face", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aio_quickbar_flirtationface {
            get {
                object obj = ResourceManager.GetObject("aio_quickbar_flirtationface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aio_quickbar_font {
            get {
                object obj = ResourceManager.GetObject("aio_quickbar_font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aio_quickbar_inputassist {
            get {
                object obj = ResourceManager.GetObject("aio_quickbar_inputassist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aio_quickbar_more {
            get {
                object obj = ResourceManager.GetObject("aio_quickbar_more", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aio_quickbar_register {
            get {
                object obj = ResourceManager.GetObject("aio_quickbar_register", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aio_quickbar_richface {
            get {
                object obj = ResourceManager.GetObject("aio_quickbar_richface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aio_quickbar_screen1 {
            get {
                object obj = ResourceManager.GetObject("aio_quickbar_screen1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aio_quickbar_screen2 {
            get {
                object obj = ResourceManager.GetObject("aio_quickbar_screen2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aio_quickbar_sendpic {
            get {
                object obj = ResourceManager.GetObject("aio_quickbar_sendpic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aio_quickbar_twitter {
            get {
                object obj = ResourceManager.GetObject("aio_quickbar_twitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AIO_SetBtn_down {
            get {
                object obj = ResourceManager.GetObject("AIO_SetBtn_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AIO_SetBtn_highlight {
            get {
                object obj = ResourceManager.GetObject("AIO_SetBtn_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AIO_SetBtn_highlight_normal {
            get {
                object obj = ResourceManager.GetObject("AIO_SetBtn_highlight_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AIO_SetBtn_normal {
            get {
                object obj = ResourceManager.GetObject("AIO_SetBtn_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap all_inside_bkg {
            get {
                object obj = ResourceManager.GetObject("all_inside_bkg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap allbtn_down {
            get {
                object obj = ResourceManager.GetObject("allbtn_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap allbtn_highlight {
            get {
                object obj = ResourceManager.GetObject("allbtn_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap away__2_ {
            get {
                object obj = ResourceManager.GetObject("away__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackPalace {
            get {
                object obj = ResourceManager.GetObject("BackPalace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_close_disable {
            get {
                object obj = ResourceManager.GetObject("btn_close_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_close_down {
            get {
                object obj = ResourceManager.GetObject("btn_close_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_close_highlight {
            get {
                object obj = ResourceManager.GetObject("btn_close_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_max_down {
            get {
                object obj = ResourceManager.GetObject("btn_max_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_max_highlight {
            get {
                object obj = ResourceManager.GetObject("btn_max_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_max_normal {
            get {
                object obj = ResourceManager.GetObject("btn_max_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_mini_down {
            get {
                object obj = ResourceManager.GetObject("btn_mini_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_mini_highlight {
            get {
                object obj = ResourceManager.GetObject("btn_mini_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_mini_normal {
            get {
                object obj = ResourceManager.GetObject("btn_mini_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_restore_down {
            get {
                object obj = ResourceManager.GetObject("btn_restore_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_restore_highlight {
            get {
                object obj = ResourceManager.GetObject("btn_restore_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_restore_normal {
            get {
                object obj = ResourceManager.GetObject("btn_restore_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_set_hover {
            get {
                object obj = ResourceManager.GetObject("btn_set_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_set_normal {
            get {
                object obj = ResourceManager.GetObject("btn_set_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_set_press {
            get {
                object obj = ResourceManager.GetObject("btn_set_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_Skin_down {
            get {
                object obj = ResourceManager.GetObject("btn_Skin_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_Skin_highlight {
            get {
                object obj = ResourceManager.GetObject("btn_Skin_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_Skin_normal {
            get {
                object obj = ResourceManager.GetObject("btn_Skin_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap busy__2_ {
            get {
                object obj = ResourceManager.GetObject("busy__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_hover {
            get {
                object obj = ResourceManager.GetObject("button_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_normal {
            get {
                object obj = ResourceManager.GetObject("button_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_press {
            get {
                object obj = ResourceManager.GetObject("button_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkbox_hightlight {
            get {
                object obj = ResourceManager.GetObject("checkbox_hightlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkbox_normal {
            get {
                object obj = ResourceManager.GetObject("checkbox_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkbox_pushed {
            get {
                object obj = ResourceManager.GetObject("checkbox_pushed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkbox_tick_highlight {
            get {
                object obj = ResourceManager.GetObject("checkbox_tick_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkbox_tick_normal {
            get {
                object obj = ResourceManager.GetObject("checkbox_tick_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkbox_tick_pushed {
            get {
                object obj = ResourceManager.GetObject("checkbox_tick_pushed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap corner_back {
            get {
                object obj = ResourceManager.GetObject("corner_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap corner_back_hover {
            get {
                object obj = ResourceManager.GetObject("corner_back_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap corner_back_press {
            get {
                object obj = ResourceManager.GetObject("corner_back_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap corner_left {
            get {
                object obj = ResourceManager.GetObject("corner_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap corner_left_hover {
            get {
                object obj = ResourceManager.GetObject("corner_left_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap corner_left_press {
            get {
                object obj = ResourceManager.GetObject("corner_left_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap corner_right {
            get {
                object obj = ResourceManager.GetObject("corner_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap corner_right_hover {
            get {
                object obj = ResourceManager.GetObject("corner_right_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap corner_right_press {
            get {
                object obj = ResourceManager.GetObject("corner_right_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap duozhanghao1 {
            get {
                object obj = ResourceManager.GetObject("duozhanghao1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap duozhanghao2 {
            get {
                object obj = ResourceManager.GetObject("duozhanghao2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap duozhanghao3 {
            get {
                object obj = ResourceManager.GetObject("duozhanghao3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap duozhanghao4 {
            get {
                object obj = ResourceManager.GetObject("duozhanghao4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap duozhanghao5 {
            get {
                object obj = ResourceManager.GetObject("duozhanghao5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap duozhanghao6 {
            get {
                object obj = ResourceManager.GetObject("duozhanghao6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frameBorderEffect_mouseDownDraw {
            get {
                object obj = ResourceManager.GetObject("frameBorderEffect_mouseDownDraw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frameBorderEffect_normalDraw {
            get {
                object obj = ResourceManager.GetObject("frameBorderEffect_normalDraw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgRjp_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("imgRjp_BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imoffline__2_ {
            get {
                object obj = ResourceManager.GetObject("imoffline__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imonline__2_ {
            get {
                object obj = ResourceManager.GetObject("imonline__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap invisible__2_ {
            get {
                object obj = ResourceManager.GetObject("invisible__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap login_inputbtn_down {
            get {
                object obj = ResourceManager.GetObject("login_inputbtn_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap login_inputbtn_highlight {
            get {
                object obj = ResourceManager.GetObject("login_inputbtn_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap login_inputbtn_normal {
            get {
                object obj = ResourceManager.GetObject("login_inputbtn_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_btn_highlight {
            get {
                object obj = ResourceManager.GetObject("menu_btn_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_btn_normal {
            get {
                object obj = ResourceManager.GetObject("menu_btn_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_check {
            get {
                object obj = ResourceManager.GetObject("menu_check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mima {
            get {
                object obj = ResourceManager.GetObject("mima", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mima_hover {
            get {
                object obj = ResourceManager.GetObject("mima_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mima_press {
            get {
                object obj = ResourceManager.GetObject("mima_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap morning {
            get {
                object obj = ResourceManager.GetObject("morning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mute__2_ {
            get {
                object obj = ResourceManager.GetObject("mute__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap night {
            get {
                object obj = ResourceManager.GetObject("night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap noon {
            get {
                object obj = ResourceManager.GetObject("noon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Norml {
            get {
                object obj = ResourceManager.GetObject("Norml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pictureBox1_Image {
            get {
                object obj = ResourceManager.GetObject("pictureBox1_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Qme__2_ {
            get {
                object obj = ResourceManager.GetObject("Qme__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap spin_normal_down {
            get {
                object obj = ResourceManager.GetObject("spin_normal_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap texture {
            get {
                object obj = ResourceManager.GetObject("texture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap texture2 {
            get {
                object obj = ResourceManager.GetObject("texture2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolbarBtnDown {
            get {
                object obj = ResourceManager.GetObject("ToolbarBtnDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolbarBtnNormal {
            get {
                object obj = ResourceManager.GetObject("ToolbarBtnNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zhuce {
            get {
                object obj = ResourceManager.GetObject("zhuce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zhuce_hover {
            get {
                object obj = ResourceManager.GetObject("zhuce_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zhuce_press {
            get {
                object obj = ResourceManager.GetObject("zhuce_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
